package bo;

import bean.*;
import dao.*;
import util.ExcelWriterUtil;
import util.JsonHelper;

import java.io.File;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * BO - Business Object xử lý toàn bộ logic phân công cán bộ coi thi.
 * 
 * Input/Output dùng Map<String, Object> (JSON-compatible) thay vì class cụ thể
 * → cho phép bất kỳ Client nào cũng giao tiếp được.
 */
public class PhanCongBO {

    private final CanBoCoiThiDAO canBoDAO = new CanBoCoiThiDAO();
    private final PhongThiNguonDAO phongThiDAO = new PhongThiNguonDAO();
    private final DotPhanCongDAO dotDAO = new DotPhanCongDAO();
    private final PhongThiPhanCongDAO phongPCDAO = new PhongThiPhanCongDAO();
    private final PhanCongChiTietDAO chiTietDAO = new PhanCongChiTietDAO();

    /**
     * Xử lý phân công từ JSON request (Map).
     * Trả về Map chứa kết quả (JSON-compatible) + 2 key đặc biệt _filePhanCong,
     * _fileGiamSat (byte[]).
     */
    public Map<String, Object> xuLyPhanCong(Map<String, Object> reqMap) {
        System.out.println("[BO] Bắt đầu xử lý phân công...");

        // ====== BƯỚC 1: PARSE & VALIDATE ======
        int m = JsonHelper.getInt(reqMap, "soGiamThi", 0);
        int n = JsonHelper.getInt(reqMap, "soPhongThi", 0);
        String tenDot = JsonHelper.getString(reqMap, "tenDot", "");

        if (m <= 0)
            return errorResult("Số giám thị (m) phải lớn hơn 0!");
        if (n <= 0)
            return errorResult("Số phòng thi (n) phải lớn hơn 0!");

        int soGiamThiCanThiet = 2 * n;
        if (m < soGiamThiCanThiet) {
            return errorResult(String.format(
                    "Số giám thị không đủ! Bạn nhập m=%d nhưng với n=%d phòng thi cần ít nhất %d giám thị (2 giám thị/phòng). "
                            + "Vui lòng nhập lại m >= %d.",
                    m, n, soGiamThiCanThiet, soGiamThiCanThiet));
        }

        // Parse danh sách cán bộ từ JSON
        List<Map<String, Object>> canBoRaw = JsonHelper.getList(reqMap, "canBo");
        if (canBoRaw == null || canBoRaw.isEmpty()) {
            return errorResult("Danh sách cán bộ rỗng! Hãy kiểm tra file Excel.");
        }
        if (canBoRaw.size() < m) {
            return errorResult(String.format("File Excel chỉ có %d cán bộ nhưng cần %d!", canBoRaw.size(), m));
        }

        // Parse danh sách phòng thi
        List<String> phongThiRaw = JsonHelper.getStringList(reqMap, "phongThi");
        if (phongThiRaw == null || phongThiRaw.size() < n) {
            int actual = (phongThiRaw != null) ? phongThiRaw.size() : 0;
            return errorResult(String.format("Chỉ có %d phòng thi nhưng cần %d.", actual, n));
        }

        // ====== BƯỚC 2: KIỂM TRA TRÙNG TÊN ĐỢT ======
        boolean autoGeneratedName = false;
        if (tenDot == null || tenDot.trim().isEmpty()) {
            tenDot = "DotThi_" + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
            autoGeneratedName = true;
            System.out.println("[BO] Tự sinh tên đợt: " + tenDot);
        } else {
            tenDot = tenDot.trim();
            try {
                DotPhanCong existing = dotDAO.findByTenDot(tenDot);
                if (existing != null) {
                    return errorResult("Tên đợt thi \"" + tenDot + "\" đã tồn tại! Vui lòng chọn tên khác.");
                }
            } catch (SQLException e) {
                return errorResult("Lỗi kiểm tra trùng tên: " + e.getMessage());
            }
        }

        try {
            // ====== BƯỚC 3: CHUẨN BỊ DỮ LIỆU (TRONG MEMORY) ======
            // Convert JSON → CanBoCoiThi list
            List<CanBoCoiThi> danhSachCanBo = new ArrayList<>();
            Set<String> seenMaGV = new HashSet<>();
            for (int i = 0; i < canBoRaw.size(); i++) {
                Map<String, Object> cb = canBoRaw.get(i);
                String maGV = JsonHelper.getString(cb, "maGV", "").trim();
                
                // Xóa trùng lặp hoặc mã rỗng
                if (maGV.isEmpty() || !seenMaGV.add(maGV)) {
                    continue; 
                }
                
                CanBoCoiThi canBo = new CanBoCoiThi();
                canBo.setMaGV(maGV);
                canBo.setHoTen(JsonHelper.getString(cb, "hoTen", ""));
                canBo.setDonViCongTac(JsonHelper.getString(cb, "donVi", ""));
                canBo.setTtNguon(i + 1);
                danhSachCanBo.add(canBo);
            }

            if (danhSachCanBo.size() < m) {
                return errorResult("Dữ liệu cán bộ hợp lệ/không trùng lặp chỉ có " 
                        + danhSachCanBo.size() + " người, không đủ " + m + " người theo yêu cầu.");
            }

            // Danh sách phòng thi
            List<PhongThiNguon> danhSachPhong = new ArrayList<>();
            for (int i = 0; i < phongThiRaw.size(); i++) {
                PhongThiNguon pt = new PhongThiNguon();
                pt.setPhongThi(phongThiRaw.get(i));
                pt.setSttNguon(i + 1);
                danhSachPhong.add(pt);
            }

            // ====== BƯỚC 4: SHUFFLE & PHÂN CÔNG ======
            System.out.println("[BO] Shuffle danh sách cán bộ...");
            List<CanBoCoiThi> pool = new ArrayList<>(danhSachCanBo);
            Collections.shuffle(pool, new Random());

            List<CanBoCoiThi> canBoDuocChon = new ArrayList<>(pool.subList(0, m));
            List<CanBoCoiThi> giamThiList = canBoDuocChon.subList(0, soGiamThiCanThiet);
            List<CanBoCoiThi> giamSatList = canBoDuocChon.subList(soGiamThiCanThiet, m);
            System.out.println("[BO] Giám thị: " + giamThiList.size() + ", Giám sát: " + giamSatList.size());

            List<String> tenPhongList = new ArrayList<>();
            for (int i = 0; i < n; i++)
                tenPhongList.add(phongThiRaw.get(i));

            // ====== BƯỚC 5: GÁN GIÁM THỊ ======
            List<PhanCongChiTiet> allChiTiet = new ArrayList<>();
            for (int i = 0; i < n; i++) {
                CanBoCoiThi gt1 = giamThiList.get(2 * i);
                PhanCongChiTiet pc1 = new PhanCongChiTiet();
                pc1.setRole(PhanCongChiTiet.ROLE_GIAMTHI1);
                pc1.setViTriTrongPhong(1);
                pc1.setMaGV(gt1.getMaGV());
                pc1.setHoTen(gt1.getHoTen());
                pc1.setTenPhong(tenPhongList.get(i));
                allChiTiet.add(pc1);

                CanBoCoiThi gt2 = giamThiList.get(2 * i + 1);
                PhanCongChiTiet pc2 = new PhanCongChiTiet();
                pc2.setRole(PhanCongChiTiet.ROLE_GIAMTHI2);
                pc2.setViTriTrongPhong(2);
                pc2.setMaGV(gt2.getMaGV());
                pc2.setHoTen(gt2.getHoTen());
                pc2.setTenPhong(tenPhongList.get(i));
                allChiTiet.add(pc2);
            }

            // ====== BƯỚC 6: GÁN GIÁM SÁT HÀNH LANG ======
            List<PhanCongChiTiet> giamSatChiTiet = new ArrayList<>();
            if (!giamSatList.isEmpty()) {
                int soGiamSat = giamSatList.size();
                int phongMoiGS = n / soGiamSat;
                int phongDu = n % soGiamSat;
                int phongIdx = 0;

                for (int g = 0; g < soGiamSat; g++) {
                    CanBoCoiThi gs = giamSatList.get(g);
                    int soPhongChoGS = phongMoiGS + (g < phongDu ? 1 : 0);

                    int fromPhong = Math.min(phongIdx, n - 1);
                    int toPhong;
                    if (soPhongChoGS <= 0) {
                        toPhong = n - 1;
                        fromPhong = n - 1;
                    } else {
                        toPhong = Math.min(phongIdx + soPhongChoGS - 1, n - 1);
                    }

                    String rangeText = (fromPhong == toPhong)
                            ? tenPhongList.get(fromPhong)
                            : "Từ " + tenPhongList.get(fromPhong) + " đến " + tenPhongList.get(toPhong);

                    PhanCongChiTiet pcgs = new PhanCongChiTiet();
                    pcgs.setRole(PhanCongChiTiet.ROLE_GIAMSAT);
                    pcgs.setViTriTrongPhong(3 + g);
                    pcgs.setRangeText(rangeText);
                    pcgs.setMaGV(gs.getMaGV());
                    pcgs.setHoTen(gs.getHoTen());
                    pcgs.setTenPhong(tenPhongList.get(fromPhong));
                    giamSatChiTiet.add(pcgs);

                    phongIdx = toPhong + 1;
                }
            }

            // ====== BƯỚC 7: GHI DB ======
            System.out.println("[BO] Logic thành công, lưu vào DB...");

            List<CanBoCoiThi> canBoFromDB = canBoDAO.insertBatch(danhSachCanBo);
            List<PhongThiNguon> phongFromDB = phongThiDAO.insertBatch(danhSachPhong);

            Map<String, Long> maGvToId = new HashMap<>();
            for (CanBoCoiThi cb : canBoFromDB) {
                maGvToId.put(cb.getMaGV(), cb.getId());
            }

            DotPhanCong dot = new DotPhanCong();
            dot.setMaDot(generateMaDot());
            dot.setTenDot(tenDot);
            dot.setSoGiamThi(m);
            dot.setSoPhongThi(n);
            dot.setTrangThai("DONE");
            long dotId = dotDAO.insert(dot);

            List<PhongThiPhanCong> danhSachPhongPC = new ArrayList<>();
            for (int i = 0; i < n; i++) {
                PhongThiPhanCong ptpc = new PhongThiPhanCong();
                ptpc.setDotPhanCongId(dotId);
                ptpc.setPhongThiNguonId(phongFromDB.get(i).getId());
                ptpc.setSoPhong(i + 1);
                ptpc.setSoLuongCanBo(2);
                ptpc.setTenPhong(tenPhongList.get(i));
                phongPCDAO.insert(ptpc);
                danhSachPhongPC.add(ptpc);
            }

            for (PhanCongChiTiet pc : allChiTiet) {
                pc.setDotPhanCongId(dotId);
                int idx = tenPhongList.indexOf(pc.getTenPhong());
                if (idx >= 0)
                    pc.setPhongThiPhanCongId(danhSachPhongPC.get(idx).getId());
                Long cbId = maGvToId.get(pc.getMaGV());
                if (cbId != null)
                    pc.setCanBoId(cbId);
            }
            for (PhanCongChiTiet pc : giamSatChiTiet) {
                pc.setDotPhanCongId(dotId);
                int idx = tenPhongList.indexOf(pc.getTenPhong());
                if (idx >= 0)
                    pc.setPhongThiPhanCongId(danhSachPhongPC.get(idx).getId());
                Long cbId = maGvToId.get(pc.getMaGV());
                if (cbId != null)
                    pc.setCanBoId(cbId);
            }

            List<PhanCongChiTiet> allToSave = new ArrayList<>(allChiTiet);
            allToSave.addAll(giamSatChiTiet);
            chiTietDAO.insertBatch(allToSave);

            // ====== BƯỚC 9: TẠO RESPONSE MAP ======
            Map<String, Object> response = new LinkedHashMap<>();
            response.put("success", true);
            response.put("message",
                    "Phân công thành công!" + (autoGeneratedName ? " (Tên đợt tự động: " + tenDot + ")" : ""));
            response.put("tenDot", tenDot);
            response.put("tongCanBo", m);
            response.put("tongGiamThi", soGiamThiCanThiet);
            response.put("tongGiamSat", giamSatList.size());
            response.put("tongPhong", n);

            // Danh sách phân công (JSON-friendly)
            List<Map<String, Object>> phanCongList = new ArrayList<>();
            int stt = 1;
            for (PhanCongChiTiet pc : allChiTiet) {
                Map<String, Object> item = new LinkedHashMap<>();
                item.put("stt", stt++);
                item.put("maGV", pc.getMaGV());
                item.put("hoTen", pc.getHoTen());
                item.put("role", pc.getRole());
                item.put("phong", pc.getTenPhong());
                phanCongList.add(item);
            }
            response.put("phanCong", phanCongList);

            // Danh sách giám sát
            List<Map<String, Object>> giamSatListResult = new ArrayList<>();
            stt = 1;
            for (PhanCongChiTiet pc : giamSatChiTiet) {
                Map<String, Object> item = new LinkedHashMap<>();
                item.put("stt", stt++);
                item.put("maGV", pc.getMaGV());
                item.put("hoTen", pc.getHoTen());
                item.put("phamVi", pc.getRangeText());
                giamSatListResult.add(item);
            }
            response.put("giamSat", giamSatListResult);

            // Không gửi file Excel — client tự lưu dựa trên dữ liệu JSON

            System.out.println("[BO] Hoàn thành!");
            return response;

        } catch (Exception e) {
            System.err.println("[BO] LỖI: " + e.getMessage());
            e.printStackTrace();
            return errorResult("Lỗi xử lý: " + e.getMessage());
        }
    }

    private Map<String, Object> errorResult(String message) {
        Map<String, Object> result = new LinkedHashMap<>();
        result.put("success", false);
        result.put("message", message);
        return result;
    }

    private void saveExcelToOutputFolder(String tenDot, String fileName, byte[] data) {
        if (data == null || data.length == 0)
            return;
        try {
            String safeName = tenDot.replaceAll("[^a-zA-Z0-9_\\-\\s\\u00C0-\\u024F\\u1E00-\\u1EFF]", "_");
            File outputDir = new File("output", safeName);
            outputDir.mkdirs();
            File outputFile = new File(outputDir, fileName);
            try (FileOutputStream fos = new FileOutputStream(outputFile)) {
                fos.write(data);
            }
            System.out.println("[BO] Đã lưu: " + outputFile.getAbsolutePath());
        } catch (Exception e) {
            System.err.println("[BO] Cảnh báo: Không thể lưu " + fileName + ": " + e.getMessage());
        }
    }

    private String generateMaDot() {
        return "DOT_" + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss"));
    }
}
